<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250713182709 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE app_user (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, username VARCHAR(180) NOT NULL, password VARCHAR(255) NOT NULL, email VARCHAR(100) NOT NULL, phone VARCHAR(25) DEFAULT NULL, description VARCHAR(255) DEFAULT NULL, locked BOOLEAN NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_88BDF3E9F85E0677 ON app_user (username)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_88BDF3E9E7927C74 ON app_user (email)');
        $this->addSql('CREATE TABLE app_user_roles (app_user_id INT NOT NULL, role_id INT NOT NULL, PRIMARY KEY(app_user_id, role_id))');
        $this->addSql('CREATE INDEX IDX_2E77EE34A3353D8 ON app_user_roles (app_user_id)');
        $this->addSql('CREATE INDEX IDX_2E77EE3D60322AC ON app_user_roles (role_id)');
        $this->addSql('CREATE TABLE audit_log (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "user" VARCHAR(100) NOT NULL, action VARCHAR(100) NOT NULL, entity_type VARCHAR(100) DEFAULT NULL, entity_id VARCHAR(100) DEFAULT NULL, target VARCHAR(100) DEFAULT NULL, details TEXT DEFAULT NULL, performed_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE batch (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, sow_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, closed BOOLEAN NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE harvest_event (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, quantity DOUBLE PRECISION NOT NULL, harvested_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, batch_id INT NOT NULL, tray_row_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_99329003F39EBE7A ON harvest_event (batch_id)');
        $this->addSql('CREATE INDEX IDX_99329003C83A8B6B ON harvest_event (tray_row_id)');
        $this->addSql('CREATE TABLE inventory_lot (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, product_name VARCHAR(100) NOT NULL, quantity DOUBLE PRECISION NOT NULL, location VARCHAR(100) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE inventory_transaction (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(50) NOT NULL, quantity DOUBLE PRECISION NOT NULL, notes JSON DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, inventory_lot_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_6C5391EA817395C ON inventory_transaction (inventory_lot_id)');
        $this->addSql('CREATE TABLE loss_event (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, quantity DOUBLE PRECISION NOT NULL, lost_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, tray_row_id INT NOT NULL, reason_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_5480D9A0C83A8B6B ON loss_event (tray_row_id)');
        $this->addSql('CREATE INDEX IDX_5480D9A059BB1592 ON loss_event (reason_id)');
        $this->addSql('CREATE TABLE loss_reason (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, reason VARCHAR(100) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE maintenance_event (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, scheduled_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, description VARCHAR(255) NOT NULL, completed BOOLEAN NOT NULL, completed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE movement_event (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, moved_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, tray_row_id INT NOT NULL, to_place_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_C614DDB2C83A8B6B ON movement_event (tray_row_id)');
        $this->addSql('CREATE INDEX IDX_C614DDB2C0FF3CB7 ON movement_event (to_place_id)');
        $this->addSql('CREATE TABLE permission (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(100) NOT NULL, description VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_E04992AA77153098 ON permission (code)');
        $this->addSql('CREATE TABLE place (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, description VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE product_workflow (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, stage VARCHAR(100) NOT NULL, notes VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE quality_code (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(100) NOT NULL, description VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE role (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(50) NOT NULL, description VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_57698A6A77153098 ON role (code)');
        $this->addSql('CREATE TABLE role_permissions (role_id INT NOT NULL, permission_id INT NOT NULL, PRIMARY KEY(role_id, permission_id))');
        $this->addSql('CREATE INDEX IDX_1FBA94E6D60322AC ON role_permissions (role_id)');
        $this->addSql('CREATE INDEX IDX_1FBA94E6FED90CCA ON role_permissions (permission_id)');
        $this->addSql('CREATE TABLE seed_lot (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, lot_code VARCHAR(100) NOT NULL, variety VARCHAR(100) NOT NULL, quantity INT NOT NULL, expiry_date DATE NOT NULL, supplier_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_CD568AC12ADD6D8C ON seed_lot (supplier_id)');
        $this->addSql('CREATE TABLE supplier (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(150) NOT NULL, contact VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE tray (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(100) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C753C79777153098 ON tray (code)');
        $this->addSql('CREATE TABLE tray_row (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, row_index INT NOT NULL, quantity DOUBLE PRECISION NOT NULL, batch_id INT NOT NULL, tray_id INT NOT NULL, place_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_E9BAEF7DF39EBE7A ON tray_row (batch_id)');
        $this->addSql('CREATE INDEX IDX_E9BAEF7DE8C42A45 ON tray_row (tray_id)');
        $this->addSql('CREATE INDEX IDX_E9BAEF7DDA6A219 ON tray_row (place_id)');
        $this->addSql('ALTER TABLE app_user_roles ADD CONSTRAINT FK_2E77EE34A3353D8 FOREIGN KEY (app_user_id) REFERENCES app_user (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE app_user_roles ADD CONSTRAINT FK_2E77EE3D60322AC FOREIGN KEY (role_id) REFERENCES role (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE harvest_event ADD CONSTRAINT FK_99329003F39EBE7A FOREIGN KEY (batch_id) REFERENCES batch (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE harvest_event ADD CONSTRAINT FK_99329003C83A8B6B FOREIGN KEY (tray_row_id) REFERENCES tray_row (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE inventory_transaction ADD CONSTRAINT FK_6C5391EA817395C FOREIGN KEY (inventory_lot_id) REFERENCES inventory_lot (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE loss_event ADD CONSTRAINT FK_5480D9A0C83A8B6B FOREIGN KEY (tray_row_id) REFERENCES tray_row (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE loss_event ADD CONSTRAINT FK_5480D9A059BB1592 FOREIGN KEY (reason_id) REFERENCES loss_reason (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE movement_event ADD CONSTRAINT FK_C614DDB2C83A8B6B FOREIGN KEY (tray_row_id) REFERENCES tray_row (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE movement_event ADD CONSTRAINT FK_C614DDB2C0FF3CB7 FOREIGN KEY (to_place_id) REFERENCES place (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE role_permissions ADD CONSTRAINT FK_1FBA94E6D60322AC FOREIGN KEY (role_id) REFERENCES role (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE role_permissions ADD CONSTRAINT FK_1FBA94E6FED90CCA FOREIGN KEY (permission_id) REFERENCES permission (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE seed_lot ADD CONSTRAINT FK_CD568AC12ADD6D8C FOREIGN KEY (supplier_id) REFERENCES supplier (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tray_row ADD CONSTRAINT FK_E9BAEF7DF39EBE7A FOREIGN KEY (batch_id) REFERENCES batch (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tray_row ADD CONSTRAINT FK_E9BAEF7DE8C42A45 FOREIGN KEY (tray_id) REFERENCES tray (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tray_row ADD CONSTRAINT FK_E9BAEF7DDA6A219 FOREIGN KEY (place_id) REFERENCES place (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE app_user_roles DROP CONSTRAINT FK_2E77EE34A3353D8');
        $this->addSql('ALTER TABLE app_user_roles DROP CONSTRAINT FK_2E77EE3D60322AC');
        $this->addSql('ALTER TABLE harvest_event DROP CONSTRAINT FK_99329003F39EBE7A');
        $this->addSql('ALTER TABLE harvest_event DROP CONSTRAINT FK_99329003C83A8B6B');
        $this->addSql('ALTER TABLE inventory_transaction DROP CONSTRAINT FK_6C5391EA817395C');
        $this->addSql('ALTER TABLE loss_event DROP CONSTRAINT FK_5480D9A0C83A8B6B');
        $this->addSql('ALTER TABLE loss_event DROP CONSTRAINT FK_5480D9A059BB1592');
        $this->addSql('ALTER TABLE movement_event DROP CONSTRAINT FK_C614DDB2C83A8B6B');
        $this->addSql('ALTER TABLE movement_event DROP CONSTRAINT FK_C614DDB2C0FF3CB7');
        $this->addSql('ALTER TABLE role_permissions DROP CONSTRAINT FK_1FBA94E6D60322AC');
        $this->addSql('ALTER TABLE role_permissions DROP CONSTRAINT FK_1FBA94E6FED90CCA');
        $this->addSql('ALTER TABLE seed_lot DROP CONSTRAINT FK_CD568AC12ADD6D8C');
        $this->addSql('ALTER TABLE tray_row DROP CONSTRAINT FK_E9BAEF7DF39EBE7A');
        $this->addSql('ALTER TABLE tray_row DROP CONSTRAINT FK_E9BAEF7DE8C42A45');
        $this->addSql('ALTER TABLE tray_row DROP CONSTRAINT FK_E9BAEF7DDA6A219');
        $this->addSql('DROP TABLE app_user');
        $this->addSql('DROP TABLE app_user_roles');
        $this->addSql('DROP TABLE audit_log');
        $this->addSql('DROP TABLE batch');
        $this->addSql('DROP TABLE harvest_event');
        $this->addSql('DROP TABLE inventory_lot');
        $this->addSql('DROP TABLE inventory_transaction');
        $this->addSql('DROP TABLE loss_event');
        $this->addSql('DROP TABLE loss_reason');
        $this->addSql('DROP TABLE maintenance_event');
        $this->addSql('DROP TABLE movement_event');
        $this->addSql('DROP TABLE permission');
        $this->addSql('DROP TABLE place');
        $this->addSql('DROP TABLE product_workflow');
        $this->addSql('DROP TABLE quality_code');
        $this->addSql('DROP TABLE role');
        $this->addSql('DROP TABLE role_permissions');
        $this->addSql('DROP TABLE seed_lot');
        $this->addSql('DROP TABLE supplier');
        $this->addSql('DROP TABLE tray');
        $this->addSql('DROP TABLE tray_row');
    }
}
